version: 2
updates:
  - package-ecosystem: "gradle"
    directories:
      - "/src/**/*"
    schedule:
      interval: "daily"
    groups:
      com.facebook.fresco:
        patterns: 
         - "com.facebook.fresco:*"
