name: Validate Build

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Update Gradle Wrapper to 8.10.2
        run: ./gradlew wrapper --gradle-version 8.10.2
        working-directory: src

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: src

      - name: Build Debug apk
        run: ./gradlew assembleDebug --stacktrace --no-daemon
        working-directory: src

      - name: Get apk path
        id: debugApk
        run: echo "apkfile=$(find src/app/build/outputs/apk/release/*.apk)" >> $GITHUB_OUTPUT
      
      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: ${{ steps.debugApk.outputs.apkfile }}
